package optimizer.algorithms;

import optimizer.common.InternalStateBase;
import optimizer.common.Solution;
import optimizer.param.Param;
import optimizer.trial.IterationResult;
import optimizer.utils.Utils;

import java.lang.Math;
import java.util.*;

import org.apache.commons.math3.special.Gamma;


public class CuckooSearch extends AbstractAlgorithm {
    InternalState state = new InternalState();
    Random rand = new Random();

    {
        this.parallelizable = ParallelExecution.GENERATION;
        this.iterationCounterCorrection = 2;
        this.optimizerParams = new LinkedList<>();
        this.optimizerParams.add(new Param(25,Integer.MAX_VALUE,1,"number_of_nests"));
        // discovery rate of cockoo eggs/solutions
        this.optimizerParams.add(new Param(0.25, 1,0, "Pa"));
        // beta
        this.optimizerParams.add(new Param(1.5, 2,1, "beta"));
        // In most cases, we can use α = O(L/10), where L is the
        //characteristic scale of the problem of interest, whereas in some cases α = O(L/100)
        this.optimizerParams.add(new Param(0.1, 100,0, "alpha"));
        this.optimizerParams.add(new Param(1, 100,0, "random_walk_step_size"));
    }

    private void initSearchSpace(List<Param> parameterMap){
        state.initSearchSpace(parameterMap);
        state.part = AlgorithmPart.second_part;
        state.swarmBestNest = -1;
    }

    private void initNests(int swarmSize) {
        state.calculateResultsForIds = new LinkedList<>();
        //initialize the nests, and add to nest array
        for (int i = 0; i < swarmSize; ++i) {
            state.swarm.add(new Nest(
                    state.dimension,
                    state.lowerBounds,
                    state.upperBounds,
                    rand));
        }
    }

    @Override
    public void updateParameters(List<Param> parameterMap, List<IterationResult> landscape) throws CloneNotSupportedException {
        int numberOfNests = ((Number)optimizerParams.get(0).getValue()).intValue();
        if (state.firstStep) {
            initSearchSpace(parameterMap);
            initNests(numberOfNests);
        } else {
            double beta = ((Number)optimizerParams.get(2).getValue()).floatValue();
            double alpha = ((Number)optimizerParams.get(3).getValue()).floatValue();
            if (state.part == AlgorithmPart.first_part) {
                /*
                Get a cuckoo randomly
                Generate a solution by L´evy flights [e.g., Eq.(9.2)]
                Evaluate its solution quality or objective value fi
                */
                for (int j = 0; j < numberOfNests; ++j) {
                    //The best solution does not change
                    if (state.swarmBestNest != j) {
                        state.swarm.get(j).levy_flights(beta,alpha, rand, state.swarmBestKnownPosition);
                        state.swarm.get(j).checkBoundsForNewPosition(state.dimension, state.lowerBounds, state.upperBounds);
                        state.calculateResultsForIds.add(j);
                    }
                }
            } else if (state.part == AlgorithmPart.second_part){
                float Pa = ((Number)optimizerParams.get(1).getValue()).floatValue();
                float randWalkStepSize = ((Number)optimizerParams.get(4).getValue()).floatValue();
                /*
                A fraction (pa) of worse nests are abandoned
                New nests/solutions are built/generated by Eq.(9.1)
                Keep best solutions (or nests with quality solutions)
                Rank the solutions and find the current best
                */
                for (int i = 0; i < numberOfNests; ++i) {
                    int j = rand.nextInt(state.swarm.size());
                    int k = rand.nextInt(state.swarm.size());
                    float epsilon = rand.nextFloat();

                    if (state.swarmBestNest != i) {
                        for (int dim = 0; dim < state.dimension; ++dim) {
                            state.swarm.get(i).newPosition[dim] =
                                    state.swarm.get(i).position[dim] + randWalkStepSize *
                                            (float) (alpha * ((Math.signum(Pa - epsilon) + 1) / 2) *  // Heaviside function
                                                    (state.swarm.get(j).position[dim] - state.swarm.get(k).position[dim]));
                        }
                        state.swarm.get(i).checkBoundsForNewPosition(state.dimension, state.lowerBounds, state.upperBounds);
                        state.calculateResultsForIds.add(i);
                    }
                }
            } else {
                // Should not happen
            }
        }
    }

    public List<Param> createParamSetup(List<Param> pattern, float[] input, int id) throws CloneNotSupportedException {
        List<Param> setup = Param.cloneParamList(pattern);
        // setup each dimension of the position
        for (int i = 0; i < setup.size(); ++i) {
            setup.get(i).setInitValue(input[i]);
            setup.get(i).setId(id);
        }
        return setup;
    }

    @Override
    public List<List<Param>> getParameterMapBatch(List<Param> pattern)throws CloneNotSupportedException {
        List<List<Param>> result = new LinkedList<>();
        if (state.firstStep) {
            for(int j = 0; j < state.swarm.size(); ++j) {
                result.add(createParamSetup(pattern, state.swarm.get(j).newPosition, j));
            }
        } else {
            for(int j = 0; j < state.calculateResultsForIds.size(); ++j) {
                int id = state.calculateResultsForIds.get(j);
                result.add(createParamSetup(pattern, state.swarm.get(id).newPosition,id));
            }
        }
        return result;
    }

    public void setResults(List<IterationResult> results) throws CloneNotSupportedException {
        if (state.firstStep) {
            int i = 0;
            for (IterationResult res : results) {
                state.swarm.get(i).actualFitness = res;
                state.swarm.get(i).position = state.swarm.get(i).newPosition.clone();
                if(state.swarm.get(i).actualFitness.betterThan(state.swarmBestFitness)) {
                    state.swarmBestFitness = state.swarm.get(i).actualFitness;
                    state.swarmBestKnownPosition = state.swarm.get(i).position.clone();
                    state.swarmBestNest = i;
                }
                ++i;
            }
        } else {
                //rewrite it, not really good in this form, prone to error
                int i = 0;
                for (IterationResult res : results) {
                    int id = state.calculateResultsForIds.get(i);
                    Nest nest = state.swarm.get(id);
                    if (nest.actualFitness.betterThan(res)) {
                        nest.actualFitness = res;
                        nest.position = nest.newPosition.clone();

                        if(nest.actualFitness.betterThan(state.swarmBestFitness)) {
                            state.swarmBestFitness = nest.actualFitness;
                            state.swarmBestKnownPosition = nest.position.clone();
                            state.swarmBestNest = i;
                        }
                    }
                    ++i;
                }
        }
    }

    public void updateGlobals() throws CloneNotSupportedException {
        state.firstStep = false;
         if (state.part == AlgorithmPart.first_part)
             state.part = AlgorithmPart.second_part;
         else
             state.part = AlgorithmPart.first_part;
         state.calculateResultsForIds.clear();
    }

    class Nest extends Solution {
        public Nest(int dim,  float[] lowerBounds, float[] upperBounds, Random rand) {
            super(dim, lowerBounds, upperBounds, rand);
        }
    }

    enum AlgorithmPart {
            first_part,
            second_part;
    }

    class InternalState extends InternalStateBase<Nest> {
        int swarmBestNest;
        List<Integer> calculateResultsForIds;
        AlgorithmPart part;
    }
}
