package optimizer.algorithms;

import optimizer.param.Param;
import optimizer.trial.IterationResult;
import optimizer.utils.Utils;

import java.lang.Math;
import java.util.*;

import org.apache.commons.math3.special.Gamma;


public class CuckooSearch extends AbstractAlgorithm {
    InternalState state = new InternalState();

    {
        this.parallelizable = ParallelExecution.GENERATION;
        this.optimizerParams = new LinkedList<>();
        this.optimizerParams.add(new Param(25,Integer.MAX_VALUE,1,"number_of_nests"));
        // discovery rate of cockoo eggs/solutions
        this.optimizerParams.add(new Param(0.25, 1,0, "Pa"));
    }

    private void initSearchSpace(List<Param> parameterMap){
        state.dimension  = parameterMap.size();
        state.lowerBounds = new float[state.dimension];
        state.upperBounds = new float[state.dimension];
        for(int i = 0; i < state.dimension; ++i) {
            state.lowerBounds[i] = ((Number)parameterMap.get(i).getLowerBound()).floatValue();
            state.upperBounds[i] = ((Number)parameterMap.get(i).getUpperBound()).floatValue();
        }
        state.part = AlgorithmPart.first_part;
        state.swarmBestNest = -1;
    }

    private void initNests(int swarmSize) {
        //array to store all parameters
        state.swarm = new ArrayList<>();
        state.calculateResultsForIds = new LinkedList<>();
        //initialize the nests, and add to nest array
        for (int i = 0; i < swarmSize; ++i) {
            state.swarm.add(new Nest(
                    state.dimension,
                    state.lowerBounds,
                    state.upperBounds));
        }
    }

    @Override
    public void updateParameters(List<Param> parameterMap, List<IterationResult> landscape) throws CloneNotSupportedException {
        int numberOfNests = ((Number)optimizerParams.get(0).getValue()).intValue();
        if (state.firstStep) {
            initSearchSpace(parameterMap);
            initNests(numberOfNests);
        } else {
            if (state.part == AlgorithmPart.first_part) {
                /*
                Get a cuckoo randomly
                Generate a solution by L´evy flights [e.g., Eq.(9.2)]
                Evaluate its solution quality or objective value fi
                */

                for (int j = 0; j < numberOfNests; ++j) {
                    if (state.swarmBestNest != j) {
                        levy_flights(state.swarm.get(j));
                        state.calculateResultsForIds.add(j);
                    }
                }
            } else if (state.part == AlgorithmPart.second_part){
                float Pa = ((Number)optimizerParams.get(1).getValue()).floatValue();
                /*
                A fraction (pa) of worse nests are abandoned
                New nests/solutions are built/generated by Eq.(9.1)
                Keep best solutions (or nests with quality solutions)
                Rank the solutions and find the current best
                */
                Random rand = new Random();
                for (Nest nest : state.swarm) {
                    if (rand.nextFloat() < Pa) {
                        //new generate solution
                        //stepsize
                    }
                }
            } else {
                // Should not happen
            }
        }
    }

    @Override
    public List<List<Param>> getParameterMapBatch(List<Param> pattern)throws CloneNotSupportedException {
        List<List<Param>> result = new LinkedList<>();
        if (state.firstStep) {
            for (Nest nest : state.swarm) {
                List<Param> setup = Param.cloneParamList(pattern);
                // setup each dimension of the position
                for (int i = 0; i < setup.size(); ++i) {
                    setup.get(i).setInitValue(nest.position[i]);
                }
                result.add(setup);
            }
        } else {
            if (state.part == AlgorithmPart.first_part) {
                state.calculateResultsForIds.forEach((Integer id) -> {
                    try {
                        List<Param> setup = Param.cloneParamList(pattern);
                        for (int i = 0; i < setup.size(); ++i) {
                            setup.get(i).setInitValue(state.swarm.get(id).newPosition[i]);
                        }
                        result.add(setup);
                    } catch (CloneNotSupportedException e) {
                        e.printStackTrace();
                    }
                });
            } else if (state.part == AlgorithmPart.second_part){

            } else {
                // Should not happen
            }

        }
        return result;
    }

    private void updateNestAndGlobalState(Nest nest, IterationResult ir) throws CloneNotSupportedException {
        nest.actualFitness = ir;
        if(nest.actualFitness.betterThan(state.swarmBestFitness)) {
            state.swarmBestFitness = nest.actualFitness;
            state.swarmBestKnownPosition = nest.position.clone();
            state.swarmBestNest = 0;
        }

    }

    public void setResults(List<IterationResult> results) throws CloneNotSupportedException {
        if (state.firstStep) {
            int i = 0;
            for (IterationResult res : results) {
                state.swarm.get(i).actualFitness = res;
                if(state.swarm.get(i).actualFitness.betterThan(state.swarmBestFitness)) {
                    state.swarmBestFitness = state.swarm.get(i).actualFitness;
                    state.swarmBestKnownPosition = state.swarm.get(i).position.clone();
                    state.swarmBestNest = i;
                }
                ++i;
            }
        } else {
            if (state.part == AlgorithmPart.first_part) {
                /*
                Choose a nest among n (say, j) randomly
                if (fi < fj ),
                    Replace j by the new solution i
                end
                */

                //rewrite it, not really good in this form, prone to error
                int i = 0;
                for (IterationResult res : results) {
                    int id = state.calculateResultsForIds.get(i);
                    Nest nest = state.swarm.get(id);
                    if (nest.actualFitness.betterThan(res)) {
                        nest.actualFitness = res;
                        nest.position = nest.newPosition.clone();

                        if(nest.actualFitness.betterThan(state.swarmBestFitness)) {
                            state.swarmBestFitness = nest.actualFitness;
                            state.swarmBestKnownPosition = nest.position.clone();
                            state.swarmBestNest = i;
                        }
                    }
                    ++i;
                }
            } else if (state.part == AlgorithmPart.second_part){
                /*
                A fraction (pa) of worse nests are abandoned
                New nests/solutions are built/generated by Eq.(9.1)
                Keep best solutions (or nests with quality solutions)
                Rank the solutions and find the current best
                */
            } else {
                // Should not happen
            }
        }
    }
    /*
    * This method sets for a nest a new position, in the
    * newPosition attribute.
    * */
    public void levy_flights(Nest nest) {
        Random rand = new Random();
        double beta = 1.5;

        double tmpdiv = Gamma.gamma((1 + beta) / 2) * beta * Math.pow(2,((beta - 1) / 2));
        double sigma = Math.pow((Gamma.gamma(1 + beta) * Math.sin(Math.PI * beta / 2)) / tmpdiv, 1 / beta) ;

        // Levy flights by Mantegna's algorithm
        double[] step = new double[state.dimension];
        for (int i = 0; i < state.dimension; ++i) {
            // u / (v)^(1/beta)
            step[i] = (rand.nextGaussian() * sigma) / Math.pow(Math.abs(rand.nextGaussian()), 1 / beta);
            }

        double alpha = 0.01;   // L/100 length scale
        // the nest is not the best in the swarm
        // apply the step
        //stepSize = alpha * step[i] * (s - best);
        //TODO: is the position used here???
        for (int i = 0; i < state.dimension; ++i) {
            nest.newPosition[i] = (float) (alpha * step[i] * (nest.position[i] - state.swarmBestKnownPosition[i]));
        }
        nest.checkBoundsForNewPosition();

    }

    public void updateGlobals() throws CloneNotSupportedException {
        state.firstStep = false;
         if (state.part == AlgorithmPart.first_part)
             state.part = AlgorithmPart.second_part;
         else
             state.part = AlgorithmPart.first_part;
         state.calculateResultsForIds.clear();
    }

    class Nest {
        float[] position;
        float[] newPosition;
        IterationResult actualFitness;


        public Nest(int dim,  float[] lowerBounds, float[] upperBounds) {
            this.position = new float[dim];
            this.newPosition = new float[dim];

            Random rand = new Random();
            for(int i = 0; i < dim; ++i) {
                float r = rand.nextFloat();
                this.position[i] = lowerBounds[i] + r * (upperBounds[i] - lowerBounds[i]);
            }
            this.actualFitness = null;
        }

        public void checkBoundsForNewPosition() {
            for (int i = 0; i < state.dimension; ++i) {
                if (newPosition[i] > state.upperBounds[i]) {
                    newPosition[i] = state.upperBounds[i];
                } else if (newPosition[i] < state.lowerBounds[i]) {
                    newPosition[i] = state.lowerBounds[i];
                }
            }
        }
    }

    enum AlgorithmPart {
            first_part,
            second_part;
    }

    class InternalState {
        ArrayList<Nest> swarm;
        List<Integer> calculateResultsForIds;
        float[] swarmBestKnownPosition;
        int swarmBestNest;
        IterationResult swarmBestFitness;
        boolean firstStep = true;
        AlgorithmPart part;

        float[] upperBounds;
        float[] lowerBounds;
        int dimension;
    }
}
